---
title: "HW2"
author: "Sangvin Kang"
date: "2024-03-13"
output: html_document
---
## HW#2_R 기본 사용법  
과제내용:
“2주차_R 기본사용법.pdf” 파일을기반으로R사용법을숙지
예제1~9에대한코드를작성하여R 마크다운보고서생성

제출방식:
생성한Github 저장소에제작한Rmd 파일을업로드

제출기한: 
3/2012:00 (차주수업일정오)까지



### 예제1
```{r question 1}
# 1-1 
sqrt(2)

# 1-2
exp(5)

# 1-3
log10(20)

# 1-4
log(20)

# 1-5
gamma(5)

# 1-6
abs(-4.5)

# 1-7
round(pi, 2)

```

### 예제2
```{r question 2}
# 2-1 정규분포: x = 5, mu = 5, sigma = 1
dnorm(5, mean = 5, sd = 1, log = FALSE)

# 2-2 지수분포: x = 1, rate = 5
dexp(1, rate = 5, log = FALSE)

# 2-3 와이블분포: x = 50, shape = 80, scale = 1.5
dweibull(50, shape = 80, scale = 1.5, log = FALSE)

```

### 예제3
```{r question 3}
# A와 b 변수 할당
A <- 5; b <- 6

# 3-1 2A + b^2
2*A + b^2

# 3-2 A^5*3^b
A^5*3^b

#할당했던 변수 제거
rm(A, b)
```

### 예제4
```{r question 4}

norm_pdf_10 <- function(x, mu, sigma) {
  value <- (1/(sigma*sqrt(2*pi)))*exp(-((x-mu)^2)/(2*sigma^2))
  return(10*value)
}

```

### 예제5
```{r question 5}
# 5-1
sum((1:100)^2)

# 5-2
prod(1:10)

# 5-3
sum(cos(((1:20)/20)*pi))

```

### 예제6
```{r question 6}

x <- 1:9
mat <- matrix(2*x, nrow=3, ncol=3, byrow=FALSE)
mat              
dimnames(mat)[[1]] <- c("A", "B", "C")
dimnames(mat)[[2]] <- c("가", "나", "다")
dimnames(mat)
mat
mat[2,3] # 2행 3열에 해당하는 값 추출

```

### 예제7
```{r question 7}

df <- data.frame(data = iris)
df1 <- data.frame(iris$Species == 'virginica')
df1

virginica_df <- df[101:150, 1:5] #종류가 virginica인 데이터 추출
virginica_df

```

### 예제8
```{r question 8}

vec1 <- iris[,3] # iris 데이터의 3번째 열
vec2 <- iris$Species
list1 <- list(vec1, vec2)
list1


```

### 예제9
```{r question 9}

y <- iris
dim(y)[1]

classification <- function(y){
    for (i in 1:dim(y)[1]){
     value <- y$Species[i]
    if(value == 'setosa'){
        print(1)
    }else if(value == 'versicolor'){
        print(2)
    }else if(value == 'virginica'){
        print(3)
    }
  }
} 
  
classification(y)

```